#include <FastLED.h>

// A simple struct to hold the color name and its corresponding CRGB value
struct ColorMap {
    const char* name;
    const CRGB color;
};

// An array of ColorMap structs for the colors you want to support
const ColorMap colorMap[] = {
 {"RED", CRGB::Red},
    {"GREEN", CRGB::Green},
    {"BLUE", CRGB::Blue},
    {"YELLOW", CRGB::Yellow},
    {"ORANGE", CRGB::Orange},
    {"PURPLE", CRGB::Purple},
    {"AMETHYST", CRGB::Amethyst},
    {"AQUA", CRGB::Aqua},
    {"AZURE", CRGB::Azure},
    {"BLACK", CRGB::Black},
    {"BLUEVIOLET", CRGB::BlueViolet},
    {"CHARTREUSE", CRGB::Chartreuse},
    {"CORAL", CRGB::Coral},
    {"CYAN", CRGB::Cyan},
    {"DARKBLUE", CRGB::DarkBlue},
    {"DARKCYAN", CRGB::DarkCyan},
    {"DARKGREEN", CRGB::DarkGreen},
    {"DARKORANGE", CRGB::DarkOrange},
    {"DARKRED", CRGB::DarkRed},
    {"DEEPSKYBLUE", CRGB::DeepSkyBlue},
    {"DODGERBLUE", CRGB::DodgerBlue},
    {"FIREBRICK", CRGB::FireBrick},
    {"FUCHSIA", CRGB::Fuchsia},
    {"GOLD", CRGB::Gold},
    {"GOLDENROD", CRGB::Goldenrod},
    {"GRAY", CRGB::Gray},
    {"GREENYELLOW", CRGB::GreenYellow},
    {"HOTPINK", CRGB::HotPink},
    {"INDIANRED", CRGB::IndianRed},
    {"INDIGO", CRGB::Indigo},
    {"LAVENDER", CRGB::Lavender},
    {"LIGHTBLUE", CRGB::LightBlue},
    {"LIGHTCORAL", CRGB::LightCoral},
    {"LIGHTCYAN", CRGB::LightCyan},
    {"LIGHTGREEN", CRGB::LightGreen},
    {"LIGHTPINK", CRGB::LightPink},
    {"LIGHTSALMON", CRGB::LightSalmon},
    {"LIGHTSEAGREEN", CRGB::LightSeaGreen},
    {"LIGHTSKYBLUE", CRGB::LightSkyBlue},
    {"LIGHTSLATEGRAY", CRGB::LightSlateGray},
    {"LIGHTSTEELBLUE", CRGB::LightSteelBlue},
    {"LIME", CRGB::Lime},
    {"LIMEGREEN", CRGB::LimeGreen},
    {"LINEN", CRGB::Linen},
    {"MAGENTA", CRGB::Magenta},
    {"MAROON", CRGB::Maroon},
    {"MEDIUMAQUAMARINE", CRGB::MediumAquamarine},
    {"MEDIUMBLUE", CRGB::MediumBlue},
    {"MEDIUMORCHID", CRGB::MediumOrchid},
    {"MEDIUMPURPLE", CRGB::MediumPurple},
    {"MEDIUMSEAGREEN", CRGB::MediumSeaGreen},
    {"MEDIUMSLATEBLUE", CRGB::MediumSlateBlue},
    {"MEDIUMSPRINGGREEN", CRGB::MediumSpringGreen},
    {"MEDIUMTURQUOISE", CRGB::MediumTurquoise},
    {"MEDIUMVIOLETRED", CRGB::MediumVioletRed},
    {"MIDNIGHTBLUE", CRGB::MidnightBlue},
    {"MINTCREAM", CRGB::MintCream},
    {"MISTYROSE", CRGB::MistyRose},
    {"MOCCASIN", CRGB::Moccasin},
    {"NAVAJOWHITE", CRGB::NavajoWhite},
    {"NAVY", CRGB::Navy},
    {"OLDLACE", CRGB::OldLace},
    {"OLIVE", CRGB::Olive},
    {"OLIVEDRAB", CRGB::OliveDrab},
    {"ORANGERED", CRGB::OrangeRed},
    {"ORCHID", CRGB::Orchid},
    {"PALEGOLDENROD", CRGB::PaleGoldenrod},
    {"PALEGREEN", CRGB::PaleGreen},
    {"PALETURQUOISE", CRGB::PaleTurquoise},
    {"PALEVIOLETRED", CRGB::PaleVioletRed},
    {"PAPAYAWHIP", CRGB::PapayaWhip},
    {"PEACHPUFF", CRGB::PeachPuff},
    {"PERU", CRGB::Peru},
    {"PINK", CRGB::Pink},
    {"PLUM", CRGB::Plum}
};
const int colorMapSize = sizeof(colorMap) / sizeof(colorMap[0]); // Number of elements in colorMap
